In [2]:
import numpy as np


In [6]:
arr1 = np.array([[16, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 17, 11],
                 [12, 13, 14, 15]])


In [7]:
arr1


array([[16,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 17, 11],
       [12, 13, 14, 15]])

In [21]:
det = np.linalg.det(arr1)
det


-1792.0000000000032

In [5]:
np.linalg.eig(arr1)


(array([-4.23921761+0.j        ,  4.11960881+0.97808983j,
         4.11960881-0.97808983j]),
 array([[-0.29340298+0.j        , -0.29794644-0.14168804j,
         -0.29794644+0.14168804j],
        [ 0.94705879+0.j        , -0.17502754-0.05555916j,
         -0.17502754+0.05555916j],
        [ 0.13036236+0.j        , -0.92597568+0.j        ,
         -0.92597568-0.j        ]]))

In [17]:
adj = np.linalg.inv(arr1)*det
adj


array([[-1.12000000e+02,  1.68000000e+02,  1.24344979e-14,
        -5.60000000e+01],
       [ 1.68000000e+02,  1.36400000e+03,  1.28000000e+02,
        -7.64000000e+02],
       [-4.24296933e-15,  1.28000000e+02, -2.56000000e+02,
         1.28000000e+02],
       [-5.60000000e+01, -1.43600000e+03,  1.28000000e+02,
         4.68000000e+02]])

In [23]:
ortho = np.array([[1/3, 2/3, -2/3],
                  [-2/3, 2/3, 1/3],
                  [2/3, 1/3, 2/3]])
ortho


array([[ 0.33333333,  0.66666667, -0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333,  0.66666667]])

In [35]:
transpose1 = ortho.transpose()
transpose1


array([[ 0.33333333, -0.66666667,  0.66666667],
       [ 0.66666667,  0.66666667,  0.33333333],
       [-0.66666667,  0.33333333,  0.66666667]])

In [37]:
np.matmul(ortho, transpose1)


array([[ 1.00000000e+00, -1.54197642e-17,  2.46716228e-17],
       [-1.54197642e-17,  1.00000000e+00, -1.23358114e-17],
       [ 2.46716228e-17, -1.23358114e-17,  1.00000000e+00]])

In [11]:
M1 = np.array([[1, 0, -1],
               [3, 1, 2]])
M2 = np.array([[1],
               [2],
               [3]])


In [14]:
np.matmul(M1, M2)


array([[-2],
       [11]])

In [26]:
M3 = np.array([[5, -3],
               [1, 0],
               [-7, 4],
               [0, 2]])
M4 = np.array([[1],
               [0]])


In [27]:
np.matmul(M3,M4)

array([[ 5],
       [ 1],
       [-7],
       [ 0]])

In [37]:
M5=np.array([[2,1,3],
[-1,1,0],
[-2,4,1]])

In [38]:
np.linalg.det(M5)

-2.999999999999998

In [39]:
I=np.linalg.inv(M5)
I
# np.linalg.pinv(I)


array([[-750599937895083/2251799813685248,
        -4128299658422957/1125899906842624,
        2251799813685249/2251799813685248],
       [-750599937895083/2251799813685248,
        -6004799503160665/2251799813685248,
        4503599627370499/4503599627370496],
       [6004799503160663/9007199254740992,
        7505999378950831/2251799813685248,
        -4503599627370499/4503599627370496]])